version: '3.7'

services:
  caddy:
    image: abiosoft/caddy
    ports:
      - 443:2015
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./certs:/etc/ssl
    links:
      - gservice
    restart: always
