version: "3.7"
services:
  gservice:
    image: csiroenvinf/geometry-data-service
    environment:
      #edit these to point to the right Postgis DB
      - "GSDB_DBNAME=${GSDB_DBNAME:-gis}"
      - "GSDB_HOSTNAME=${GSDB_HOSTNAME:-db}"
      - "GSDB_PORT=${GSDB_PORT:-5432}"
      - "GSDB_USER=${GSDB_USER:-jon}"
      - "GSDB_PASS=${GSDB_PASS:-jon}"
    ports:
     - "${PORT:-3000}:3000"

  db:
    image: kartoza/postgis:12.0
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - "POSTGRES_DBNAME=${POSTGRES_DBNAME:-gis,asgs16}"
      - "POSTGRES_USER=${POSTGRES_USER:-jon}"
      - "POSTGRES_PASS=${POSTGRES_PASS:-jon}"
      - "ALLOW_IP_RANGE=0.0.0.0/0"
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      - "POSTGRES_MULTIPLE_EXTENSIONS=${POSTGRES_MULTIPLE_EXTENSIONS:-postgis,hstore,postgis_topology}"
    ports:
      - "${POSTGIS_EXPOSED_PORT:-25432}:5432"

  loader:
      build: ./load_data
      command: tail -f /dev/null
      #command: sh -c './wait-for-it.sh db:5432 -t 0 -- ./entrypoint.sh'


volumes:
   postgis-data:

